[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "nginx -g 'daemon off;'"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[nixpacks]
start = "nginx -g 'daemon off;'"
